<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE paises [
<!ELEMENT paises (pais+)>
<!ELEMENT pais (nombre , unionEuropea? , otan?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT unionEuropea EMPTY>
<!ELEMENT otan EMPTY>
<!-- Cambios, definir el elemento paises y añadir el ? en unionEuropea ya que puede estar o no estar y el elemento nombre no es EMPTY sino (#PCDATA)-->

]>
<paises>
  <pais>
    <nombre>España</nombre>
    <unionEuropea/>
    <otan/>
  </pais>
  <pais>
    <nombre>Noruega</nombre>
    <otan/>
  </pais>
  <pais>
    <nombre>Austria</nombre>
    <unionEuropea/>
  </pais>
</paises>
